example {
  passwd  should_be_much_stronger;    # Password
  type  tun;            # IP tunnel
  proto tcp;            # TCP protocol
  compress no;
  encrypt  no;          # Encryption
  device vtun-server;

  up {
        # Connection is Up
        ifconfig "%% 10.11.12.14 pointopoint 10.11.12.13 mtu 1450";
  };
}   
