example {
  passwd  should_be_much_stronger;    # Password
  type  tun;            # IP tunnel
  proto tcp;            # TCP protocol
  device vtun-client;
  up {
        ifconfig "%% 10.11.12.13 pointopoint 10.11.12.14 mtu 1450";
  };
}
